Upload region backup
qiniu/go-sdk pull request #74
Opened 2022-09-05 08:22 UTC by YangSen-qn

2022-09-05 08:43 UTC, bachue commented on internal/freezer/freezer.go
> +func (i *freezer) Freeze(itemId string, duration int) error {
@YangSen-qn `duration` 考虑直接设计成 `time.Duration` 类型？

2022-09-05 08:44 UTC, bachue commented on internal/hostprovider/host_provider.go
> +func (a *arrayHostProvider) Freeze(host string, cause error, duration int) error {
@YangSen-qn `duration` 考虑直接设计成 `time.Duration` 类型？

2022-09-05 12:39 UTC, bachue commented on storage/region_group.go
> +	locker             sync.Mutex
@YangSen-qn 这里用 `sync.RWMutex` 比较好，下面的方法除了 `SwitchRegion()` 以外都是只读的

2022-09-05 13:02 UTC, bachue commented on storage/upload_source.go
> +	Reload() error
@YangSen-qn 你的意思是 `rewind` 吧？

2022-09-13 06:31 UTC, bachue approved these changes

2022-09-13 06:35 UTC, bachue approved these changes

2022-09-22 08:57 UTC, lyyyuna requested changes

2022-09-22 08:57 UTC, lyyyuna commented on storage/region_uc_v2_test.go
> +package storage
// +build integration

2022-09-23 02:20 UTC, lyyyuna approved these changes

2022-09-23 09:35 UTC, merged